'use client'

import { Suspense, use, useCallback, useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { Check, ChevronLeft, Copy, Loader2 } from 'lucide-react'
import { QRCodeSVG } from 'qrcode.react'

import { ApiError } from '@/lib/api-error'
import {
  getOrder,
  verifyInvoiceStatus,
} from '@/lib/api/commerce'
import { useSession } from '@/lib/auth/use-session'
import type { Order } from '@/types/shared'

// BOLT-11 invoices generated by /api/orders expire 15 min after issue
// per the Commerce CLAUDE.md spec. We compute remaining time from
// order.createdAt since the API doesn't expose the expiry directly.
const INVOICE_TTL_MS = 15 * 60 * 1000

// Mirror the demo BTC/NGN rate for the sats-side display.
const NGN_PER_BTC = 145_000_000n
const SATS_PER_BTC = 100_000_000n

function formatSatsNumber(satsStr: string): string {
  try {
    return Number(BigInt(satsStr)).toLocaleString('en-NG')
  } catch {
    return '0'
  }
}

function formatNgnFromSats(satsStr: string): string {
  try {
    const sats = BigInt(satsStr)
    const ngn = (sats * NGN_PER_BTC) / SATS_PER_BTC
    return `₦${Number(ngn).toLocaleString('en-NG')}`
  } catch {
    return '₦0'
  }
}

function formatMmSs(ms: number): string {
  if (ms <= 0) return '00:00'
  const totalSeconds = Math.floor(ms / 1000)
  const mins = Math.floor(totalSeconds / 60)
  const secs = totalSeconds % 60
  return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`
}

function CheckoutPageContent({ params }: { params: Promise<{ orderId: string }> }) {
  const router = useRouter()
  const { orderId } = use(params)
  const { user, isLoading: isSessionLoading } = useSession()

  // Auth gate. The order detail endpoint 401s anyway, but kicking the
  // user out at mount avoids a confusing flash of the loading skeleton.
  useEffect(() => {
    if (!isSessionLoading && !user) {
      router.push('/signin')
    }
  }, [isSessionLoading, user, router])

  const [order, setOrder] = useState<Order | null>(null)
  const [fetchState, setFetchState] = useState<'loading' | 'ready' | 'error' | 'forbidden'>('loading')
  const [pollError, setPollError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  // Re-rendered every second so the countdown ticks. We compute remaining
  // time from order.createdAt + INVOICE_TTL_MS rather than counting down a
  // local timer — survives navigation away and back.
  const [now, setNow] = useState(() => Date.now())

  // Fetch the order on mount.
  useEffect(() => {
    if (!user) return
    let cancelled = false
    setFetchState('loading')
    getOrder(orderId)
      .then(res => {
        if (cancelled) return
        setOrder(res)
        setFetchState('ready')
      })
      .catch(err => {
        if (cancelled) return
        if (err instanceof ApiError && err.statusCode === 403) {
          setFetchState('forbidden')
        } else {
          setFetchState('error')
        }
      })
    return () => {
      cancelled = true
    }
  }, [orderId, user])

  // Tick the clock every second for the countdown display.
  useEffect(() => {
    if (!order || order.status !== 'PENDING') return
    const id = setInterval(() => setNow(Date.now()), 1000)
    return () => clearInterval(id)
  }, [order])

  // Derived values for the populated state.
  const expiresAt = order ? new Date(order.createdAt).getTime() + INVOICE_TTL_MS : 0
  const msLeft = Math.max(0, expiresAt - now)
  const isExpired = order?.status === 'PENDING' && msLeft <= 0
  const isPaid =
    order?.status === 'PAID' ||
    order?.status === 'SHIPPED' ||
    order?.status === 'DELIVERED'
  const isCancelled = order?.status === 'CANCELLED'

  // Auto-redirect to /success if the order is already paid when we
  // arrive (e.g., user navigated back here after settlement).
  useEffect(() => {
    if (order && isPaid) {
      router.replace(`/checkout/${order.id}/success`)
    }
  }, [order, isPaid, router])

  // Polling. While the order is PENDING and the invoice hasn't expired,
  // hit /api/lightning/verify on a schedule: every 2s for the first 5
  // minutes, then every 5s. Stops on settlement or expiry.
  const pollHandle = useRef<number | null>(null)
  const scheduleNextPoll = useCallback((paymentHash: string, elapsedMs: number) => {
    const interval = elapsedMs < 5 * 60 * 1000 ? 2000 : 5000
    pollHandle.current = window.setTimeout(async () => {
      try {
        const res = await verifyInvoiceStatus(paymentHash)
        setPollError(null)
        if (res.settled && res.order) {
          setOrder(res.order)
          return // settled — useEffect above will redirect
        }
      } catch (err) {
        // Soft fail — log + retry on next tick. Don't block the user.
        console.warn('Invoice poll failed', err)
        if (err instanceof ApiError && err.statusCode === 401) {
          router.push('/signin')
          return
        }
        setPollError('Lost connection to the payment server. Retrying…')
      }
      scheduleNextPoll(paymentHash, elapsedMs + interval)
    }, interval)
  }, [router])

  useEffect(() => {
    if (!order || order.status !== 'PENDING' || isExpired || !order.paymentHash) return
    const elapsed = Date.now() - new Date(order.createdAt).getTime()
    scheduleNextPoll(order.paymentHash, elapsed)
    return () => {
      if (pollHandle.current !== null) {
        window.clearTimeout(pollHandle.current)
        pollHandle.current = null
      }
    }
  }, [order, isExpired, scheduleNextPoll])

  const handleCopyInvoice = () => {
    if (!order?.invoiceBolt11) return
    navigator.clipboard.writeText(order.invoiceBolt11)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  // LOADING (session + first fetch)
  if (isSessionLoading || fetchState === 'loading') {
    return <CheckoutShell><CheckoutSkeleton /></CheckoutShell>
  }

  // FORBIDDEN — someone else's order
  if (fetchState === 'forbidden') {
    return (
      <CheckoutShell>
        <div className="text-center py-20">
          <h1 className="font-serif text-3xl font-normal mb-2">This isn’t your order.</h1>
          <p className="font-sans text-base text-muted mb-6 max-w-sm mx-auto">
            You can only check out an order you started.
          </p>
          <Link
            href="/marketplace"
            className="inline-block bg-primary text-primary-foreground px-6 py-3 rounded font-sans font-medium hover:opacity-90 transition-opacity"
          >
            Back to marketplace
          </Link>
        </div>
      </CheckoutShell>
    )
  }

  // ERROR (network / 404)
  if (fetchState === 'error' || !order) {
    return (
      <CheckoutShell>
        <div className="text-center py-20">
          <h1 className="font-serif text-3xl font-normal mb-2">We couldn’t load this order.</h1>
          <p className="font-sans text-base text-muted mb-6 max-w-sm mx-auto">
            Check your connection and try again, or head back to the marketplace.
          </p>
          <Link
            href="/marketplace"
            className="inline-block bg-primary text-primary-foreground px-6 py-3 rounded font-sans font-medium hover:opacity-90 transition-opacity"
          >
            Back to marketplace
          </Link>
        </div>
      </CheckoutShell>
    )
  }

  // CANCELLED (cron expired it from under us, or buyer cancelled)
  if (isCancelled) {
    return (
      <CheckoutShell>
        <div className="text-center py-20">
          <h1 className="font-serif text-3xl font-normal mb-2">This order was cancelled.</h1>
          <p className="font-sans text-base text-muted mb-6 max-w-sm mx-auto">
            Start a new order from the product page.
          </p>
          <Link
            href="/marketplace"
            className="inline-block bg-primary text-primary-foreground px-6 py-3 rounded font-sans font-medium hover:opacity-90 transition-opacity"
          >
            Back to marketplace
          </Link>
        </div>
      </CheckoutShell>
    )
  }

  // PAID — the useEffect above is racing to redirect. Render a brief
  // confirmation while the navigation kicks in.
  if (isPaid) {
    return (
      <CheckoutShell>
        <div className="text-center py-20">
          <Loader2 className="w-8 h-8 animate-spin text-accent mx-auto mb-4" />
          <p className="font-serif text-xl">Payment received…</p>
        </div>
      </CheckoutShell>
    )
  }

  // PENDING — the live invoice view.
  const item = order.items[0]
  const totalNgn = formatNgnFromSats(order.totalSats)
  const totalSats = formatSatsNumber(order.totalSats)
  const lightningUrl = order.invoiceBolt11 ? `lightning:${order.invoiceBolt11}` : '#'

  return (
    <CheckoutShell>
      <div className="space-y-6">
        {/* Product preview */}
        {item && (
          <div className="bg-white border border-border rounded-lg p-4 flex items-center gap-4">
            {item.productImage && (
              <img
                src={item.productImage}
                alt={item.productTitle}
                className="w-16 h-16 rounded object-cover shrink-0"
              />
            )}
            <div className="flex-1 min-w-0">
              <p className="font-serif text-base text-foreground truncate">
                {item.productTitle}
              </p>
              <p className="font-sans text-xs text-muted">Order {order.id}</p>
            </div>
          </div>
        )}

        {/* Total + listening status + countdown */}
        <div className="text-center space-y-1">
          <p className="font-sans text-xs uppercase tracking-widest text-muted">
            Pay with Lightning
          </p>
          <p className="font-serif text-5xl text-accent tabular-nums">{totalNgn}</p>
          <p className="font-sans text-sm text-muted tabular-nums">{totalSats} sats</p>
          {isExpired ? (
            <p className="font-sans text-sm text-error pt-2">Invoice expired</p>
          ) : (
            <div className="pt-3 space-y-2">
              <div
                role="status"
                aria-live="polite"
                className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-accent/10 text-accent"
              >
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                <span className="font-sans text-sm font-medium">
                  Listening for your payment…
                </span>
              </div>
              <p className="font-sans text-xs text-muted tabular-nums">
                Invoice expires in {formatMmSs(msLeft)}
              </p>
            </div>
          )}
        </div>

        {!isExpired && order.invoiceBolt11 && (
          <>
            {/* QR code — 256px square per the design's "scannable from across a room" guidance */}
            <div className="bg-white border border-border rounded-lg p-6 flex justify-center">
              <QRCodeSVG
                value={order.invoiceBolt11}
                size={256}
                level="M"
                marginSize={0}
              />
            </div>

            {/* Actions */}
            <div className="grid grid-cols-2 gap-3">
              <button
                type="button"
                onClick={handleCopyInvoice}
                className="flex items-center justify-center gap-2 py-3 px-4 rounded font-sans text-sm font-medium bg-white border border-border text-foreground hover:bg-input/30 transition-colors"
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4" /> Copied
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" /> Copy invoice
                  </>
                )}
              </button>
              <a
                href={lightningUrl}
                className="flex items-center justify-center py-3 px-4 rounded font-sans text-sm font-medium bg-primary text-primary-foreground hover:opacity-90 transition-opacity"
              >
                Open in wallet
              </a>
            </div>

            {pollError && (
              <p
                role="alert"
                className="font-sans text-xs text-muted text-center"
              >
                {pollError}
              </p>
            )}

            <p className="font-sans text-xs text-muted text-center">
              Scan with any Lightning wallet — Phoenix, Wallet of Satoshi, Breez. Most
              payments confirm in 5–30 seconds after you tap Send. Keep this page open.
            </p>
          </>
        )}

        {isExpired && (
          <div className="text-center py-6 space-y-4">
            <p className="font-sans text-base text-muted max-w-sm mx-auto">
              The 15-minute payment window passed. Start a new order from the product page
              to try again.
            </p>
            <Link
              href="/marketplace"
              className="inline-block bg-primary text-primary-foreground px-6 py-3 rounded font-sans font-medium hover:opacity-90 transition-opacity"
            >
              Back to marketplace
            </Link>
          </div>
        )}
      </div>
    </CheckoutShell>
  )
}

function CheckoutShell({ children }: { children: React.ReactNode }) {
  const router = useRouter()
  return (
    <div className="bg-background min-h-screen text-foreground">
      <div className="sticky top-0 z-40 bg-background border-b border-border">
        <div className="px-5 py-3 flex items-center">
          <button
            onClick={() => router.back()}
            className="p-3 -m-3 hover:bg-input rounded transition-colors"
            aria-label="Go back"
          >
            <ChevronLeft className="w-6 h-6 text-foreground" strokeWidth={2} />
          </button>
        </div>
      </div>
      <main className="mx-auto max-w-2xl px-5 py-8">{children}</main>
    </div>
  )
}

function CheckoutSkeleton() {
  return (
    <div className="space-y-6" aria-busy="true" aria-label="Loading order">
      <div className="bg-white border border-border rounded-lg p-4 flex items-center gap-4">
        <div className="w-16 h-16 rounded bg-input animate-pulse" />
        <div className="flex-1 space-y-2">
          <div className="h-4 w-3/4 bg-input rounded animate-pulse" />
          <div className="h-3 w-1/2 bg-input rounded animate-pulse" />
        </div>
      </div>
      <div className="text-center space-y-2">
        <div className="h-3 w-32 bg-input rounded mx-auto animate-pulse" />
        <div className="h-12 w-40 bg-input rounded mx-auto animate-pulse" />
        <div className="h-3 w-24 bg-input rounded mx-auto animate-pulse" />
      </div>
      <div className="bg-white border border-border rounded-lg p-6 flex justify-center">
        <div className="w-64 h-64 bg-input animate-pulse" />
      </div>
    </div>
  )
}

export default function CheckoutPage({ params }: { params: Promise<{ orderId: string }> }) {
  return (
    <Suspense fallback={<div className="bg-background min-h-screen" />}>
      <CheckoutPageContent params={params} />
    </Suspense>
  )
}
